name: mutation testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - test/**

jobs:
  stryker4jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 15
          cache: 'sbt'
      - name: Create Stryker4jvm config
        run: echo 'stryker4jvm{reporters=["console","dashboard"],base-dir="core",dashboard.module="core"}' > stryker4jvm.conf
      - name: Run Stryker4jvm
        run: sbt 'project stryker4jvm; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  command-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 15
          cache: 'sbt'
      - name: Create Stryker4jvm config
        run: echo 'stryker4jvm{reporters=["console","dashboard"],base-dir="command-runner",dashboard.module="command-runner"}' > stryker4jvm.conf
      - name: Run Stryker4jvm
        run: sbt 'project stryker4jvm-command-runner; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  maven-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'maven'
      - name: Publish Stryker4jvm maven deps locally
        run: sbt 'publishM2Local'
      - name: Run Stryker4jvm
        run: |
          cd maven
          mvn -B --no-transfer-progress stryker4jvm:run
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
